Jk�V<?php exit; ?>a:1:{s:7:"content";O:8:"stdClass":24:{s:2:"ID";i:441;s:11:"post_author";s:1:"2";s:9:"post_date";s:19:"2015-10-26 09:24:40";s:13:"post_date_gmt";s:19:"2015-10-26 09:24:40";s:12:"post_content";s:4510:"<h3><a href="http://localhost:8081/paytmbigbo/wp-content/uploads/2015/10/Commonly-Used-Terms1.png"><img class="aligncenter size-full wp-image-986" src="http://localhost:8081/paytmbigbo/wp-content/uploads/2015/10/Commonly-Used-Terms1.png" alt="Commonly-Used-Terms" width="1004" height="77" /></a></h3>
<h4></h4>
<h4>Order ID</h4>
An order ID is generated every time an order is placed by a customer. This is a unique identifier for any order placed at Paytm. Since a single order might comprise of multiple items so an order ID might contain multiple item IDs.

&nbsp;
<h4>Item ID</h4>
An item ID is an ID given to a product when an order is created. It is contained within an order id.

&nbsp;
<h4>Product ID</h4>
A product ID is unique identifier for a product - merchant combination. Same product being sold by different merchants will have different PIDs depending on the merchant.

&nbsp;
<h4>Merchant ID</h4>
A unique number given to every merchant.

&nbsp;
<h4>Merchant SKU ID</h4>
Merchant SKU [stock-keeping unit] ID is the ID given to a product by the merchant.

&nbsp;
<h4>Paytm SKU ID</h4>
Paytm SKU [stock-keeping unit] ID is an ID given by Paytm to a product since the Merchant SKU ID are generated by the Seller and may coincide.

&nbsp;
<h4>Category ID</h4>
An ID given to a category.

&nbsp;
<h4>Fulfillment ID</h4>
Fulfillment ID is used to track each packet shipped individually.

<em>For example</em> – Let’s say a single order comprises 2 power banks and 1 mobile phone. If the Seller decides to ship each item individually, then, even though each of the packets will have the same Order ID, MID and delivery address, they will have the same Fulfillment IDs are generated. This is to make but to tracking the individual packets simpler as they mapped to the AWB number which are used by delivery partners.

&nbsp;
<h4>Shipment ID</h4>
Same as <strong>Fulfillment ID</strong>.

&nbsp;
<h4>AWB number<strong> </strong></h4>
Air Way Bill numbers are used to track the order and know exactly where the order is in the delivery process. It is mostly used by the delivery partners.

&nbsp;
<h4>Manifest ID</h4>
The manifest for multiple orders is processed together. These orders all have the same manifest ID. All orders with the same manifest ID are given to one courier partner together. So the manifest ID is used to track the ‘package’ of multiple items given to the courier partner all with different order IDs, fulfillment ID, invoices, but the same Manifest IDs.

&nbsp;
<h4>LMD &amp; Non – LMD</h4>
Fulfilment service provided by Paytm is called <a href="http://localhost:8081/paytmbigbo/index.php/lmd-vs-nlmd/">Last Mile Delivery</a> (LMD).

&nbsp;
<h4>SS &amp; NSS</h4>
<a href="http://localhost:8081/paytmbigbo/index.php/ss-vs-nss/">Shipable Service</a> are geographical areas which are covered under the LMD coverage area and returns pickup areas.

&nbsp;
<h4>RPC</h4>
Paytm has recently introduced its state of the art <a href="http://localhost:8081/paytmbigbo/index.php/rpc/">Return Processing Centers</a> (RPCs) across the country.

&nbsp;
<h4>Return Policy ID</h4>
Every item listed on Paytm is listed against a particular return policy which is identified by a <a href="http://localhost:8081/paytmbigbo/index.php/return-policies/">Return Policy Number</a>. This in turn defines the return related terms and conditions for the customer.

&nbsp;
<h4>Marketing Commission</h4>
The percentage commission of the Selling Price charged by Paytm Marketplace for every order is called the <a href="http://localhost:8081/paytmbigbo/index.php/commissions-2/">Marketing Commission</a>.

&nbsp;
<h4>Transfer Price</h4>
At times, Paytm may decide the Selling Price of a particular listing belonging to a seller. In such cases, the seller decides the Transfer Price which will get transferred to him/her as payout once the product gets sold.

&nbsp;
<h4>Payment Gateway Commission</h4>
This is the percentage <a href="http://localhost:8081/paytmbigbo/index.php/various-fee/">commission</a> levied on the money which the customer is transacting for buying the product.

&nbsp;
<h4>Seller Panel<strong> </strong></h4>
This is the interface which is used by the seller in order to upload his products, manage his listings, process orders and perform other vital tasks related to a selling on Paytm. This <a href="http://localhost:8081/paytmbigbo/index.php/training/">panel</a> can help your track and manage your orders and sales along with approving commissions.

&nbsp;

&nbsp;";s:10:"post_title";s:19:"Commonly Used Terms";s:12:"post_excerpt";s:0:"";s:11:"post_status";s:7:"publish";s:14:"comment_status";s:6:"closed";s:11:"ping_status";s:6:"closed";s:13:"post_password";s:0:"";s:9:"post_name";s:21:"commonly-used-terms-2";s:7:"to_ping";s:0:"";s:6:"pinged";s:0:"";s:13:"post_modified";s:19:"2015-10-26 09:24:40";s:17:"post_modified_gmt";s:19:"2015-10-26 09:24:40";s:21:"post_content_filtered";s:0:"";s:11:"post_parent";i:0;s:4:"guid";s:45:"http://localhost:8081/paytmbigbo/?page_id=441";s:10:"menu_order";i:0;s:9:"post_type";s:4:"page";s:14:"post_mime_type";s:0:"";s:13:"comment_count";s:1:"0";s:6:"filter";s:3:"raw";}}