<div class="cma-login">
 <!--   <?php _e('Please log in to post questions/answers', 'cm-answers'); ?>:<br />
    <div class="cma-login-wp"><?php wp_login_form(); ?></div>
    <?php if( get_option('users_can_register') ) {
		echo sprintf('<p><a href="%s">%s</a></p>', esc_attr(wp_registration_url()), __('Register'));
	} ?>-->
	<?php if(!is_user_logged_in()){ ?>Click here to <a href="<?php echo wp_login_url(); ?>" title="Login">Login</a>/<a href="<?php echo wp_registration_url(); ?>">Register</a> <?php } ?>
</div>